export const data =
{
    products: [
        {
            name: 'Free shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            img: './images/shirt3.jpg',
            price: 60,
            brand: 'Nike',
            rating: 4,
            numReview: 34,
            countInStock: 15,
            description: 'The Best  shirt evert',
        },
        {
            name: 'Reymond shirt',
            slug: 'slim-shirt',
            category: 'Shirts',
            img: './images/shirt2.jpg',
            price: 30,
            brand: 'Reymond',
            rating: 3,
            numReview: 324,
            countInStock: 45,
            description: 'Reymond  shirt ',
        },
        {
            name: 'zara shirt',
            slug: 'formal-shirt',
            category: 'Shirts',
            img: './images/shirt1.jpg',
            price: 40,
            brand: 'Zara',
            rating: 5,
            numReview: 524,
            countInStock: 340,
            description: 'Zara  shirt ',
        },
        {
            name: 'Golf Pants',
            slug: 'golf-pant',
            category: 'Pant',
            img: './images/pant1.jpg',
            price: 60,
            brand: 'Adidas',
            rating: 3,
            numReview: 67,
            countInStock: 7,
            description: 'The brand pant',
        },
        {
            name: 'Classis Pants',
            slug: 'classis-pant',
            category: 'Pant',
            img: './images/pant2.jpg',
            price: 230,
            brand: 'Adidas',
            rating: 4.5,
            numReview: 637,
            countInStock: 47,
            description: 'The classic pant',
        },
        {
            name: 'jeans Pants',
            slug: 'jeans-pant',
            category: 'Pant',
            img: './images/pant3.jpg',
            price: 40,
            brand: 'Buffelo',
            rating: 2,
            numReview: 37,
            countInStock: 37,
            description: 'The best jeans ever pant',
        },
    ]
}
